name: 'Set up Android Manifest Merger'
description: 'Downloads Android Manifest Merger by distriqt and adds a wrapper launcher to PATH.'
author: 'OussamaTeyib'

branding:
  icon: 'package'
  color: 'green'

inputs:
  version:
    description: 'Manifest Merger version to install. If not specified, downloads the latest GitHub release.'
    required: false

runs:
  using: 'node24'
  main: 'dist/index.js'